# Maintainer: Yoyo <admin@yzzi.icu>

pkgname=yoyo-settings-git
_pkgname=yoyo-settings
pkgver=0.9
pkgrel=1
pkgdesc="System Settings application for Yoyo Desktop"
arch=('x86_64')
url="https://github.com/yoyo-os/settings"
license=('GPL')
groups=('yoyo-yyds-git')
depends=('yoyo-fishui-git' 'fontconfig' 'freetype2' 'icu' 'kcoreaddons' 'yoyo-libyoyo-git' 'modemmanager-qt' 'networkmanager-qt')
makedepends=('extra-cmake-modules' 'ninja' 'qt5-tools' 'git')
provides=("$_pkgname")
conflicts=("$_pkgname")
source=("git+$url.git")
sha512sums=('SKIP')

pkgver() {
  cd settings
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd settings

  cmake -DCMAKE_INSTALL_PREFIX=/usr .
  make
}

package() {
  cd settings
  make DESTDIR="$pkgdir" install
}